spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
    url: jdbc:h2:mem:db
    username: desenvolvimento
    password: desenvolvimento
    driver-class-name: 'org.h2.Driver'
  jpa:
    database: h2
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  flyway:
    enabled: false
server:
  port: 8080


api.logradouro: http://localhost:${wiremock.server.port}