spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
    url: jdbc:mysql://localhost:3307/logradouro
    username: user
    password: pwd
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/testdata
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
server:
  port: 9090

